### ISSUE TITLE
CLI-Run simulator from Docker registry by default #358 

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-cli#48]
`genlayer init` and `genlayer up` should both run by default with the docker registry image

A bit more context in https://github.com/yeagerai/genlayer-simulator/issues/358

**Comment by cristiam86** [comment]
Created issue on CLI project: https://github.com/orgs/yeagerai/projects/11/views/2?pane=issue&itemId=78285242
