### ISSUE TITLE
Display error with x-terminal-emulator

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-cli#50]
Some users have faced an issue regarding problems to find displays in terminal emulators 

- https://discord.com/channels/1237055789441487021/1276142313797845063/1276142418877743210
- https://discord.com/channels/1237055789441487021/1275847428477550806/1275878556228124683

![image](https://github.com/user-attachments/assets/caeb5240-5a46-4a9c-8c8f-ee508584c9ce)

**Comment by cristiam86** [comment]
![Image](https://github.com/user-attachments/assets/b8cb70bb-44cf-4758-bfba-9b3a68d64991)
